// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignDiaryTag(arg1) {
  return window['go']['db']['FrontQuery']['AssignDiaryTag'](arg1);
}

export function FtsDiarySearch(arg1) {
  return window['go']['db']['FrontQuery']['FtsDiarySearch'](arg1);
}

export function GetAllDiaries() {
  return window['go']['db']['FrontQuery']['GetAllDiaries']();
}

export function GetAllDiariesLimit(arg1) {
  return window['go']['db']['FrontQuery']['GetAllDiariesLimit'](arg1);
}

export function GetDeletedDiaries(arg1) {
  return window['go']['db']['FrontQuery']['GetDeletedDiaries'](arg1);
}

export function GetDiariesCount() {
  return window['go']['db']['FrontQuery']['GetDiariesCount']();
}

export function GetDiaryByID(arg1) {
  return window['go']['db']['FrontQuery']['GetDiaryByID'](arg1);
}

export function GetDiaryByTag(arg1) {
  return window['go']['db']['FrontQuery']['GetDiaryByTag'](arg1);
}

export function GetNoTagDiaries(arg1) {
  return window['go']['db']['FrontQuery']['GetNoTagDiaries'](arg1);
}

export function InitDB(arg1, arg2) {
  return window['go']['db']['FrontQuery']['InitDB'](arg1, arg2);
}

export function InsertDiaryEntry(arg1) {
  return window['go']['db']['FrontQuery']['InsertDiaryEntry'](arg1);
}

export function InsertDiaryRecord(arg1) {
  return window['go']['db']['FrontQuery']['InsertDiaryRecord'](arg1);
}

export function OpenDB(arg1, arg2) {
  return window['go']['db']['FrontQuery']['OpenDB'](arg1, arg2);
}

export function UpdateDiaryEntryByID(arg1) {
  return window['go']['db']['FrontQuery']['UpdateDiaryEntryByID'](arg1);
}
