// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AssignDiaryTag(arg1:db.AssignDiaryTagParams):Promise<db.Tag>;

export function FtsDiarySearch(arg1:string):Promise<Array<db.Diary>>;

export function GetAllDiaries():Promise<Array<db.Diary>>;

export function GetAllDiariesLimit(arg1:db.GetAllDiariesLimitParams):Promise<Array<db.Diary>>;

export function GetDeletedDiaries(arg1:db.GetDeletedDiariesParams):Promise<Array<db.Trash>>;

export function GetDiariesCount():Promise<number>;

export function GetDiaryByID(arg1:number):Promise<db.Diary>;

export function GetDiaryByTag(arg1:db.GetDiaryByTagParams):Promise<Array<db.Diary>>;

export function GetNoTagDiaries(arg1:db.GetNoTagDiariesParams):Promise<Array<db.Diary>>;

export function InsertDiaryEntry(arg1:db.InsertDiaryEntryParams):Promise<db.Diary>;

export function InsertDiaryRecord(arg1:string):Promise<db.Diary>;

export function OpenDB(arg1:string,arg2:string):Promise<void>;

export function UpdateDiaryEntryByID(arg1:db.UpdateDiaryEntryByIDParams):Promise<db.Diary>;
