// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFilePath():Promise<string>;

export function GetDBPath():Promise<string>;

export function IsDev():Promise<boolean>;

export function Platform():Promise<string>;

export function SetDBPath(arg1:string):Promise<void>;
