// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFilePath() {
  return window['go']['main']['App']['ChooseFilePath']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function IsDev() {
  return window['go']['main']['App']['IsDev']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function SetDBPath(arg1) {
  return window['go']['main']['App']['SetDBPath'](arg1);
}
