// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Configuration struct {
	ID    int64
	Key   sql.NullString
	Value sql.NullString
}

type Diary struct {
	ID        int64
	Entry     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DiaryFt struct {
	Entry string
}

type Tag struct {
	ID      int64
	DiaryID int64
	Tag     string
}

type Trash struct {
	ID             int64
	DiaryID        int64
	DiaryEntry     string
	DiaryCreatedAt time.Time
	DiaryUpdatedAt time.Time
	CreatedAt      time.Time
}
